---
title: "Lab_1"
output: html_notebook
---
1. Vectores y Matrices
```{r}
#1.1
student_1 <- c(50.4, 62.3, 92.1, 77.6, TRUE)
student_2 <- c(41.7, 87.9, 75.3, 72.4, FALSE)
student_3 <- c(30.3, 67.8, 69.3, 71.2, FALSE)
student_4 <- c(65.4, 85.1, 92.3, 96.8, TRUE)
student_5 <- c(70.4, 88.2, 95.2, 90.7, TRUE)

#1.2
students_vector <- c(student_1, student_2, student_3, student_4, student_5)

#1.3
students_matrix <- matrix(students_vector, nrow=5, byrow=TRUE)
```
2. Nombrando una Matriz
```{r}
#2.1
name_students <- c('Lily Brown', 'Davis Moore', 'Susan Taylor', 'Mike Jones', 'Tom Hill')
name_courses_legal_age <- c('TIC', 'Accounting', 'Psychology', 'Ethics',
'Legal_age')

#2.2
rownames(students_matrix) <- name_students
colnames(students_matrix) <- name_courses_legal_age
students_matrix
```
3. rowSums, cbind
```{r}
#3.1
total_grande_student <- rowSums(students_matrix[,1:4])
total_grande_student

#3.2
result_students <- cbind(students_matrix, total_grande_student)
result_students
  
```
4. Elementos de una matriz
```{r}
#4.1
filas_vector <- c(1,3,5)
columnas_vector <- c(2,4)
selected_elements <- result_students[filas_vector,columnas_vector]
selected_elements
```
5. Data Frames
```{r}
#5.1
students_grades_df <- data.frame(result_students)
students_grades_df

#5.2
subset_df <- subset(students_grades_df, subset=Accounting>80)
subset_df

```
Funciones, Condicionales y Bucles
```{r}
#6.1
students_projection <- function(){
  for (row in 1:nrow(result_students)){
  for (col in 1:ncol(result_students)-1){
    print (paste("on row", row, "and column", col, "contains", result_students[row,col]))
  }
}
}
students_projection()

#6.2
students_projection <- function(){
  for (row in 1:nrow(result_students)){
  for (col in 1:ncol(result_students)-1){
    if (result_students[row,col] <= 45){
       print('Student at risk')
    }
  }
}
}
students_projection()

```

